const SHOWTIMES_FOR_DURATION_TWO_HOUR = ["10:30AM", "01:00PM", "03:30PM"];

const SHOWTIMES_FOR_DURATION_ABOVE_TWO_HOUR = ["12:30PM", "03:30PM"];

const MOVIE_SHOW_TIMES = {
  TWO_HOUR: SHOWTIMES_FOR_DURATION_TWO_HOUR,
  ABOVE_TWO_HOUR: SHOWTIMES_FOR_DURATION_ABOVE_TWO_HOUR,
};

export default MOVIE_SHOW_TIMES;
